import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
test('landing assets stay local, cleared, and privacy bounded',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),js=readFileSync(path.join(root,'site/app.js'),'utf8');assert.doesNotMatch(html,/<(?:img|script|link)[^>]+(?:src|href)=["']https?:/i);assert.doesNotMatch(html,/assets\/(?:creator-micro-2\.avif|og-hardware\.jpg)/i);assert.match(html,/href="https:\/\/worklouder\.cc\/creator-micro-2"/);assert.match(html,/rel="icon" href="favicon\.svg"/);assert.doesNotMatch(html,/<form\b/i);assert.doesNotMatch(html,/role="radio(?:group)?"/);assert.doesNotMatch(js,/fetch\(|XMLHttpRequest|WebSocket|document\.cookie|localStorage|sessionStorage/);assert.match(html,/Synthetic demo/)})
test('landing renders every capability once',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),record=JSON.parse(readFileSync(path.join(root,'site/capabilities.json'),'utf8')),rendered=[...html.matchAll(/data-capability="([^"]+)"/g)].map(m=>m[1]).sort();assert.deepEqual(rendered,record.capabilities.map(x=>x.id).sort());assert.equal(new Set(rendered).size,rendered.length)})
test('board exposes the exact four-row Creator Micro 2 silhouette',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8');assert.equal((html.match(/class="key agent/g)??[]).length,6);assert.equal((html.match(/class="key action/g)??[]).length,4);const order=['data-control="Dial left"','data-slot="0"','data-slot="1"','aria-label="Planar toggle and joystick on the right"','data-slot="2"','data-slot="3"','data-slot="4"','data-slot="5"','data-control="Amplify"','data-control="Verify"','data-control="Polish"','data-control="Advance"','data-control="Layer and connection touch"','data-control="Voice"','data-control="Send / Continue"','data-control="Attention"'];let cursor=-1;for(const marker of order){const next=html.indexOf(marker,cursor+1);assert.ok(next>cursor,`${marker} should follow the prior physical control`);cursor=next}assert.match(html,/transparent-key/);assert.doesNotMatch(html,/<(?!button\b)[a-z][^>]*\bdata-control=/i)})
test('demo is hardware optional and keyboard plus numpad friendly',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),js=readFileSync(path.join(root,'site/app.js'),'utf8');for(const marker of ['data-view="hardware"','data-view="deck"','data-scene="build"','data-scene="review"','data-scene="quiet"','aria-keyshortcuts='])assert.match(html,new RegExp(marker));for(const marker of ["addEventListener('keydown'",'Numpad1','Numpad9','Numpad0','event.preventDefault()','event.repeat'])assert.match(js,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(js,/fetch\(|XMLHttpRequest|WebSocket|document\.cookie|localStorage|sessionStorage/)})
test('demo keyboard shortcuts remain usable after pointer selection without stealing native activation',()=>{const js=readFileSync(path.join(root,'site/app.js'),'utf8');assert.match(js,/interactiveTarget && \(event\.code === 'Space' \|\| event\.code === 'Enter'\)/);assert.match(js,/control\.focus\(\{ preventScroll: true \}\)/)})
test('unreleased integration and procurement claims remain explicit',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),llms=readFileSync(path.join(root,'site/llms.txt'),'utf8');assert.match(html,/Four proposed delivery modes/);assert.match(html,/Actual task navigation remains Codex-owned/);assert.doesNotMatch(html,/One tap selects an assigned task/);assert.match(html,/An inquiry is not an offer, SLA, or procurement eligibility/);assert.match(html,/No compliance certification or government authorization is claimed/);assert.match(llms,/contract is proposed/);assert.doesNotMatch(llms,/\.agents\/skills\/ashlr-delivery/)})
