import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
test('landing assets stay local, cleared, and privacy bounded',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),js=readFileSync(path.join(root,'site/app.js'),'utf8');assert.doesNotMatch(html,/<(?:img|script|link)[^>]+(?:src|href)=["']https?:/i);assert.doesNotMatch(html,/assets\/(?:creator-micro-2\.avif|og-hardware\.jpg)/i);assert.match(html,/href="https:\/\/worklouder\.cc\/creator-micro-2"/);assert.match(html,/rel="icon" href="favicon\.svg"/);assert.doesNotMatch(html,/<form\b/i);assert.doesNotMatch(html,/role="radio(?:group)?"/);assert.doesNotMatch(js,/fetch\(|XMLHttpRequest|WebSocket|document\.cookie|localStorage|sessionStorage/);assert.match(html,/Synthetic demo/)})
test('landing renders every capability once',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),record=JSON.parse(readFileSync(path.join(root,'site/capabilities.json'),'utf8')),rendered=[...html.matchAll(/data-capability="([^"]+)"/g)].map(m=>m[1]).sort();assert.deepEqual(rendered,record.capabilities.map(x=>x.id).sort());assert.equal(new Set(rendered).size,rendered.length)})
test('board exposes the exact four-row Creator Micro 2 control groups',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),css=readFileSync(path.join(root,'site/styles.css'),'utf8'),js=readFileSync(path.join(root,'site/app.js'),'utf8');assert.equal((html.match(/class="key agent/g)??[]).length,6);assert.equal((html.match(/class="key action/g)??[]).length,4);const order=['data-control="Dial left"','data-slot="0"','data-slot="1"','aria-label="Four-direction planar stick on the right"','data-slot="2"','data-slot="3"','data-slot="4"','data-slot="5"','data-control="Amplify"','data-control="Verify"','data-control="Polish"','data-control="Advance"','data-control="Layer and connection touch"','data-control="Voice"','data-control="Copy next brief"','data-control="Attention"'];let cursor=-1;for(const marker of order){const next=html.indexOf(marker,cursor+1);assert.ok(next>cursor,`${marker} should follow the prior physical control`);cursor=next}assert.equal((html.match(/class="joy-(?:up|right|down|left)"/g)??[]).length,4);assert.doesNotMatch(`${html}\n${css}\n${js}`,/Planar press|joy-press|aria-keyshortcuts="J"|\['KeyJ'/);assert.match(html,/transparent-key/);assert.doesNotMatch(html,/<(?!button\b)[a-z][^>]*\bdata-control=/i)})
test('hero uses a clearly synthetic interactive four-by-four twin',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),js=readFileSync(path.join(root,'site/app.js'),'utf8');assert.equal((html.match(/data-hero-target=/g)??[]).length,16);assert.match(html,/Interactive screen twin/);assert.match(html,/Original CSS illustration—not a product photograph/);assert.match(html,/data-hero-target="Dial press"[\s\S]*data-hero-target="Chat 1"[\s\S]*data-hero-target="Chat 2"[\s\S]*data-hero-target="Planar right"/);assert.match(html,/data-hero-target="Layer and connection touch"[\s\S]*data-hero-target="Voice"[\s\S]*data-hero-target="Copy next brief"[\s\S]*data-hero-target="Attention"/);assert.match(js,/heroControls\.forEach/);assert.match(js,/scrollIntoView\(\)/)})
test('demo is hardware optional and keyboard plus numpad friendly',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),js=readFileSync(path.join(root,'site/app.js'),'utf8');for(const marker of ['data-view="hardware"','data-view="deck"','data-scene="build"','data-scene="review"','data-scene="quiet"','aria-keyshortcuts='])assert.match(html,new RegExp(marker));for(const marker of ["addEventListener('keydown'",'Numpad1','Numpad9','Numpad0','event.preventDefault()','event.repeat'])assert.match(js,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(js,/fetch\(|XMLHttpRequest|WebSocket|document\.cookie|localStorage|sessionStorage/)})
test('demo keyboard shortcuts remain usable after pointer selection without stealing native activation',()=>{const js=readFileSync(path.join(root,'site/app.js'),'utf8');assert.match(js,/interactiveTarget && \(event\.code === 'Space' \|\| event\.code === 'Enter'\)/);assert.match(js,/control\.focus\(\{ preventScroll: true \}\)/)})
test('unreleased integration and procurement claims remain explicit',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8'),llms=readFileSync(path.join(root,'site/llms.txt'),'utf8');assert.match(html,/Four proposed delivery modes/);assert.match(html,/Actual task navigation remains Codex-owned/);assert.doesNotMatch(html,/One tap selects an assigned task/);assert.match(html,/An inquiry is not an offer, SLA, or procurement eligibility/);assert.match(html,/No compliance certification or government authorization is claimed/);assert.match(llms,/contract is proposed/);assert.doesNotMatch(llms,/\.agents\/skills\/ashlr-delivery/)})
test('first-run flow separates connection from physical acceptance and destructive recovery',()=>{const html=readFileSync(path.join(root,'site/index.html'),'utf8');const order=['Power + data','Choose white wired mode','Select layer 1','Check Settings, then restart','Prove a visible action','Recover without wiping'];let cursor=-1;for(const marker of order){const next=html.indexOf(marker,cursor+1);assert.ok(next>cursor,`${marker} should follow the prior commissioning step`);cursor=next}assert.match(html,/Connected is the start—not proof that a key works/);assert.match(html,/double-tap a different assigned Agent Key within 350 ms/);assert.match(html,/one tap can switch without foregrounding/);assert.match(html,/Quit Karabiner or Logitech Options\+ if it has Input Monitoring/);assert.match(html,/Reset settings[\s\S]*profiles are backed up[\s\S]*deletion is intentional/);assert.match(html,/https:\/\/learn\.chatgpt\.com\/docs\/features\/codex-micro/);assert.match(html,/https:\/\/worklouder\.cc\/micro-setup/)})
